name: Linux Build

# on:
#   push:
#     branches: [ master ]
  # pull_request:
  #   branches: [ master ]
on:
  push:
    paths:
      - '**.cpp'
      - '**.sln'
      - 'makefile'

jobs:

  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make Linux
      run: |
        rm -rf release/contains 2>/dev/null
        rm -rf release 2>/dev/null
        make
        chmod 755 release/contains
        mkdir -p  debian/contains/usr/bin/
        cp -f release/contains debian/contains/usr/bin/
        contains_linux_md5_text='{\n\t"schemaVersion": 1,\n\t"color": "2E9778",\n\t"label": "contains MD5",\n\t"message": "PLACEHOLDER",\n\t"labelColor": "1d1d1d",\n\t"style": "for-the-badge",\n\t"namedLogo": "linux"\n}'
        if ! [[ -d "docs/json" ]]; then
          mkdir -p docs/json
        fi
        if ! [[ -f "docs/json/contains_linux_md5.json" ]]; then
          touch docs/json/contains_linux_md5.json
        fi
        echo -e "$contains_linux_md5_text" > docs/json/contains_linux_md5.json
        sed -i "s/\"message\": \".*\"/\"message\": \"$(md5sum release/contains | cut -d' ' -f 1)\"/g" docs/json/contains_linux_md5.json
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Built Linux Binary
        add_options: '--force'
        push_options: '--force'
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        tag: 1.0.0
        name: Stable Release
        prerelease: False
        artifacts: "release/contains"
        token: ${{ secrets.GITHUB_TOKEN }}
